services:
  api:
    image: ms-patient-ehr:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - MS_SECURITY=http://ms-security:3002/api/v1
    ports:
      - "3003:3003"
    expose:
      - "3003"
    networks:
      medcore-network:
        aliases:
          - ms-patient-ehr
    restart: unless-stopped

networks:
  medcore-network:
    external: true
